name: Shaarli CI
on: [push, pull_request]
jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Gettext
        run: |
          sudo apt-get update && \
          sudo apt-get install -y gettext

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, xml, curl, mbstring, intl, gettext, ldap
          tools: composer:v2

      - name: Check PHP version
        run: php -v

      - name: Setup Composer from PHP version + update
        run: composer config --unset platform && composer config platform.php ${{ matrix.php-versions }}

      - name: Update dependencies for PHP 8.x
        run: |
          composer update

      - name: Install locales
        run: |
          sudo apt-get update && \
          sudo apt-get install -y locales

      - name: Set locales
        run: |
          sudo locale-gen de_DE.utf8 && \
          sudo locale-gen en_US.utf8 && \
          sudo locale-gen fr_FR.utf8

      - name: Check locales
        run: locale -a

      - name: Clean up
        run: make clean

      - name: Check permissions
        run: make check_permissions

      - name: Run PHPCS
        run: make code_sniffer

      - name: Run tests
        run: make all_tests

  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Yarn install
        run: yarnpkg install

      - name: Verify successful frontend builds
        run: yarnpkg run build

      - name: JS static analysis
        run: make eslint

      - name: Linter for SASS syntax
        run: make sasslint

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build documentation
        run: make htmldoc

  trivy-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run trivy scanner on repository (non-blocking)
        run: make test_trivy_repo TRIVY_EXIT_CODE=0
